objs-y :=

objs-y += aeabi_uidivmod.o
objs-y += aeabi_uldivmod.o
objs-y += divmodsi4.o
objs-y += jmp.o
objs-y += udivmodsi4.o
objs-y += aeabi_div0.o
objs-y += udivmoddi4.o

obj-y += $(patsubst %, lib/c/src/arch-arm/%, ${objs-y})
